/*******************************************************************************
FileName:       I2CGetStatus.c
Processor:      PIC18
Compiler:       Microchip MPLAB C18 v3.34 or higher

Copyright © 2010 released Microchip Technology Inc.  All rights
reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
*******************************************************************************/

#include "I2CPrivate.h"



#define I2C_STATUS_MASK_CONTROL     (I2C_RECEIVER_OVERFLOW | I2C_WRITE_COLLISION)
#define I2C_STATUS_MASK_STATUS      (I2C_BUFFER_FULL | I2C_UPDATE_ADDRESS | I2C_MASTER_TRANSMITTER_BUSY | I2C_START | I2C_STOP | I2C_SLAVE_DATA)


/*******************************************************************************
  Function:
    I2C_STATUS I2CGetStatus ( I2C_MODULE id )

  Summary:
    Routine to provide the current status of the I2C module

  Description:
    This routine provides a bitmask of the current status values for the I2C
    module.

  Precondition:
    None

  Parameters:
    id      - Identifies the desired I2C module

  Returns:
    The return value is a bitmask generated by a bit-wise OR of the I2C_STATUS
    values that are currently set.

  Example:
    <code>
    status = I2CGetStatus(I2C1);
    if(I2C_ARBITRATION_LOSS & status)
    {
        // Handle arbitration loss
        //...
        I2CClearStatus(I2C1, I2C_ARBITRATION_LOSS);
    }
    </code>

  Remarks:
  *****************************************************************************/

I2C_STATUS I2CGetStatus ( I2C_MODULE id )
{
    I2C_REGISTERS * const   i2cRegisters = i2cBase[id];
    I2C_STATUS              status;
    UINT32                  control;

    // Read the status and control registers
    status  = i2cRegisters->SSPxSTAT.value & I2C_STATUS_MASK_STATUS;
    control = i2cRegisters->SSPxCON1.value & I2C_STATUS_MASK_CONTROL;

    return(status | control);
}
